apiVersion: v1
kind: Service
metadata:
  name: themis-eureka
  labels:
    app: themis-eureka
spec:
  ports:
  - port: 9010
  selector:
    app: themis-eureka


#--------------------------------------------------------

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: themis-eureka
  labels:
    app: themis-eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: themis-eureka
    spec:
      containers:
      - name: themis-eureka
        image: 192.168.1.101:5005/oxchains/themis-eureka:latest
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
        ports:
        - containerPort: 9010